import PDFDocument from "pdfkit";

export const generateReportPDF = (report: any): Promise<Buffer> => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers: Buffer[] = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    // ===== HEADER =====
    doc.fontSize(20).text("Learner Performance Report", {
      align: "center",
    });

    doc.moveDown(2);

    doc.fontSize(12).text(`Learner: ${report.user.name}`);
    doc.text(`Email: ${report.user.email}`);
    doc.text(`Status: ${report.status}`);
    doc.text(`Overall Average: ${report.overallAverage.toFixed(2)}%`);

    doc.moveDown(2);

    doc.fontSize(14).text("Quizzes:", { underline: true });
    doc.moveDown();

    // ===== QUIZ LIST =====
    report.quizzes.forEach((q: any, index: number) => {
      const lessonTitle = q.quiz?.lesson?.title || "No Lesson";
      const quizTitle = q.quiz?.title || "No Quiz Title";

      doc.fontSize(12).text(`${index + 1}. Lesson: ${lessonTitle}`);
      doc.text(`   Quiz: ${quizTitle}`);
      doc.text(`   Score: ${q.score}`);
      doc.text(`   Percentage: ${q.percentage.toFixed(2)}%`);
      doc.text(`   Passed: ${q.passed ? "Yes" : "No"}`);

      doc.moveDown();
    });

    doc.moveDown(2);
    doc.text("Generated by Digital Learning System", {
      align: "center",
    });

    doc.end();
  });
};
